### ISSUE TITLE
Memory leak in shaderc_compiler_initialize

### ISSUE THREAD

**Issue by friesofdoom** [google/shaderc#1052]
static shaderc_util::GlslangInitializer* initializer =
      new shaderc_util::GlslangInitializer;

 is never deleted.

This causes a whole chain reaction of memory leaks.

**Comment by zoddicus** [comment]
per libshaderc_util/include/libshaderc_util/compiler.h, GlslangInitializer is a Singleton, so though this is technically memory leak, it isn't a bug. Admittedly the Singleton pattern has not been correctly implemented here, so that should be corrected.

This all should in theory go away with resolving #679 

I am going to confirm whether I should refactor this to be a proper Singleton, or if I should just rip it all out.

**Comment by zoddicus** [comment]
Just looked at the bot configs for what sanitizers we are running. There is an ASAN config that is part of kokoro:run, which wouldn't catch leaks, though will catch some other issues.

We should probably also add a LSAN bot at least to catch leaks. For other sanitizers, MSAN & UBSAN could potentially be useful, but if I recall correctly they are more difficult to setup/noisy.

I have filed #1053 for looking into increasing the sanitizer coverage.

**Comment by dneto0** [comment]
FYI.  Years ago our team discussed the tradeoffs of leaking these singleton objects.  At the time we chose to deliberately leak them rather than deal with the complexity of correctly releasing them, e.g. in the presence of multiple threads.

The nifty counter (just looked it up), relies C++ constructors and destructors for objects of static duration (so they're initialized before main() and destroyed after exit).  That is against Google C++ style for important reasons.  https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables 

In any case, I'm happy for @zoddicus  to safely eliminate the mutex around Glslang, which will eliminate one singleton.

Looking at the stack trace, and drawing on experience from over a decade ago, text processing in the C++ standard IO stream uses allocated objects to manage locale translations, particularly for text and numbers.  That may be what's leaking here.  If that's the case, it may be out of our hands, and is really the responsibility of the underlying C++ runtime.

**Comment by zoddicus** [comment]
Marking this issue as closed, since #1059 reduces the leak to a single std::mutex, and we have filed other work items to improve sanitizer coverage.
