### ISSUE TITLE
Extensions?

### ISSUE THREAD

**Issue by charles-r-earp** [google/shaderc#1163]
It would be nice to be able to add extensions in the same way that one adds macros. The user specifies the name of the extension and the behavior (Enable, Require, Warn, Disable). It then gets inserted after the version line. I can probably PR this but I wanted to know if this was something that could be added.

**Comment by dneto0** [comment]
That's manipulating the source text, rather than an option fro compiling it. Also, it would be specific to GLSL, I think. (If that's what you're getting at.)

The adding of a macro symbol definition is available from the glslc command line because that functionality is available in GCC and Clang and MSVC.

**Comment by charles-r-earp** [comment]
Macros do not work for this purpose because extensions must appear before macros.
