### ISSUE TITLE
glslc splicing in far too many digits on constants for float/half values

### ISSUE THREAD

**Issue by alecazam** [google/shaderc#1190]
Float precision with 6 digits can't hold this, but yet most of our shaders have this in place of 0.2 spliced into the transpiled Metal code.  With half it's even worse, and there's not that much precision.  Can half even hold 3-4 digits of decimal mantissa?  This just make the code hard to read, and not line up with the original.  Would be nicer to have the original constants instead of these approximations.

1. 0.20000000298023223876953125

2. Original glsl code:
occ > half(0.00001)				

Transpiled to Metal:
occ > half(9.953975677490234375e-06)

3. Original glsl
vec3 grayColor = vec3( dot( baseColor.rgb, 0.5 * vec3( 0.3, 0.6, 1.0 ) ) );
	
Transpiled:	
float3 grayColor = float3(dot(baseColor.xyz, float3(0.1500000059604644775390625, 0.300000011920928955078125, 0.5)));

**Comment by dneto0** [comment]
0.1 and 0.2 are not exactly representable in binary floating point formats.  That's why you're seeing the extra digits: the number has been pushed through a representation that has forced an approximation.  In particular this affects binary32 ('float') and binary16 ('half') floating point formats.

I might recommend hex floats, except that MSL is based on C++14;  but C++ hex floats were introduced in C++17.

There's nothing to do here.
