### ISSUE TITLE
Support for compiling to C/C++ header

### ISSUE THREAD

**Issue by Themaister** [google/shaderc#214]
For many applications, it would be very convenient to be able to compile GLSL directly to a SPIR-V encoded as a static const uint32_t[].

In smaller projects, and especially for embedded/mobile, it is very useful to bake the SPIR-V shaders directly into the binary.

**Comment by dekimir** [comment]
Shaderc follows closely the glslang design here, and glslang [only has functions](https://github.com/KhronosGroup/glslang/blob/master/SPIRV/GlslangToSpv.h#L45) to compile into a `vector<unsigned int>` for now.

**Comment by Themaister** [comment]
True, but emitting a C header is essentially just a different way of dumping the u32 vector to disk, so it shouldn't affect glslang at all. It is standalone enough that this could even be a separate binary.

**Comment by dekimir** [comment]
Sorry, I thought you were proposing a libshaderc interface extension.  But it sounds like you just want to take the `spv_binary` and print its elements into a `.h` file?  That's doable in ~4 lines of code, I think.  Or are you proposing that we add a flag to glslc to do it automatically?

**Comment by Themaister** [comment]
I was thinking about adding some flags to glslc to dump out a header instead of raw .spv.
Again, trivial to do, but it's very convenient.

**Comment by dekimir** [comment]
@Themaister: makes sense.  We'll come up with a suitable flag name and implement.

**Comment by dneto0** [comment]
I think we should mimic GCC's -masm=dialect option.
https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html#index-masm_003d_0040var_007bdialect_007d-2832

So you'd use -S to emit assembly and -masm=c to say you want C source.

One difficulty is in saying what variable name you want for the result. You might want to do this with several binaries.
So how about we just emit a brace-initialization list of values, and it's up to you to wrap the result.
eg. the output could be
```
  {  0x07230203, 0x00010000, 0x00080000, 1, 0 }
```
And you'd put that into a "binary.inc"
Then in your C code (or C++ code) you'd say
```
static uint32_t empty_binary[] = 
#include "binary.inc"
;
```

The point is that all the decisions about integrating it into the rest of your program are left to you, rather than adding lots of config parameters to glslc.

In this case I'd be tempted to use -masm=c-init-list as the option.

**Comment by Themaister** [comment]
That's a solid solution. It would be nice to avoid having to specify the array name on CLI, and it's also nice to avoid having to specify static/constness of the array in question. It can also be used as an initializer list in C++11 that way too.

**Comment by antiagainst** [comment]
#218 is landed. Closing.

**Comment by Themaister** [comment]
Works great. Thanks :)
