### ISSUE TITLE
How to build includes without enabling "GL_GOOGLE_include_directive" extension? 

### ISSUE THREAD

**Issue by acterhd** [google/shaderc#259]
Hello. I have problems with Nvidia. How to disable output of "GL_GOOGLE_include_directive" codes in productive shaders?

**Comment by antiagainst** [comment]
Hi @acterhd,

Do you mean removing the `OpSourceExtension GL_GOOGLE_include_directive` line in the generated SPIR-V binary module? That actually can be done via the [`-Os`](https://github.com/google/shaderc/tree/master/glslc#452--o0--os) option on glslc (or `SetOptimizationLevel` for the library API). Yeah, that also runs some other optimization stuff, but I think it's beneficial for productive code. More fine-grained controlling is something not supported yet and should be a TODO.

Hope this solves your problem. Let me know if I am not answering your question. Thanks!

**Comment by acterhd** [comment]
In `glslc` none this flag...

**Comment by antiagainst** [comment]
Hmm, now I'm suspecting that the driver compiler is using debug instruction for some meaningful stuff (use `OpName` for interface matching, etc. which is why the above errors since `-Os` removes all debug instructions), which is not supposed to be the case: https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html#OpSourceExtension. (Notice the "no semantic impact and can safely be removed from a module" part, which means, with or without `OpSourceExtension`/`OpName`, the module should just work fine.)

Could you provide the original error from the driver compiler before applying `-Os`? Thanks!

**Comment by acterhd** [comment]
```
./shaders/voxelizer/voxelizer.frag.spv

Fragment info
-------------
(0) : fatal error C9999: *** exception during compilation ***
```

**Comment by acterhd** [comment]
Okay.... I can't load any compute shader from SPIR-V in OpenGL...

**Comment by antiagainst** [comment]
Oh, glad to see you've figured out this by yourself. Sorry didn't provide much help. I'll close this for now.

**Comment by acterhd** [comment]
I anyway can't load SPIR-V modules...

**Comment by dneto0** [comment]
Loading SPIR-V into OpenGL is a recently-ratified extension.
https://www.opengl.org/registry/specs/ARB/gl_spirv.txt 
I'd first check to make sure that your driver supports that extension.
