### ISSUE TITLE
Issue with scalers in the mpv project related to shaderc

### ISSUE THREAD

**Issue by PapricaJim** [google/shaderc#450]
I'm not sure how related this is to shaderc or spirv-tools, but users have reported that reverting to this commit of shaderc: https://github.com/google/shaderc/commit/583fb1326b02c9bec31096b93bf5938e0d16346b, fixes the issue, so I posted the initial issue report here.

See https://github.com/mpv-player/mpv/issues/5695, for more details.

**Comment by antiagainst** [comment]
Hey @PapricaJim, thanks for the report!

Have you tried to use the latest SPIRV-Tools to see whether that helps? We have a few bug fixes went in recently in SPIRV-Tools.

If not, could you share a shader so that we can diagnose and fix?

**Comment by PapricaJim** [comment]
> Have you tried to use the latest SPIRV-Tools to see whether that helps? We have a few bug fixes went in recently in SPIRV-Tools.

Yes, I've built it this commit: https://github.com/KhronosGroup/SPIRV-Tools/commit/3020104ff25a0f661e7818bd49fbf5f23e0b0e98
The problem persists.

> If not, could you share a shader so that we can diagnose and fix?

I'm not a developer of mpv myself, so I honestly don't know where to look for that, but it's one of the built in scalers mpv uses which causes this.
Which is probably somewhere in here?: https://github.com/mpv-player/mpv/tree/master/video/out/vulkan

One of their developers can probably explain this way better than I ever could.

**Comment by antiagainst** [comment]
We can look into this if a shader is provided. Turning off optimization would serve as a workaround in the meanwhile? (Before https://github.com/google/shaderc/commit/2a0f3a3e348072ad6a9e53874188146b895705ba, we are basically doing no optimizations even the following is requested.)

https://github.com/mpv-player/mpv/blob/c33faee6bac27102cd04897ceec9ab040473d9ba/video/out/gpu/spirv_shaderc.c#L34-L35

Or maybe you can try using `shaderc_optimization_level_performance` to see if that works.

Thanks!

**Comment by shinchiro** [comment]
The problem still exist with `shaderc_optimization_level_performance `. Only `shaderc_optimization_level_zero` actually works

**Comment by antiagainst** [comment]
Yeah, `shaderc_optimization_level_zero` means turning off optimization essentially.

**Comment by shinchiro** [comment]
Shader `ewa_lanczossharp` (probably?) which gave the problem:
https://0x0.st/suv7.txt

Anyway, ping @haasn as I'm not sure whether the shader is the right one

**Comment by haasn** [comment]
Yes that seems like the right shader

**Comment by haasn** [comment]
I've removed the noise and formatted it: https://0x0.st/suYo.txt

In theory, `glslangValidator -Os` on the command line should also trigger this, thus making it a glslang bug, no? (Can't test since the version of glslang I'm using apparently doesn't allow optimization)

**Comment by dneto0** [comment]
LocalMultiStoreElim was changed to use a new SSA rewriter (https://github.com/KhronosGroup/SPIRV-Tools/commit/735d8a579ecb6c5b5d41c2a81d695b49f7bd3248#diff-52df82c3ea36eaca2d92e40fd2a6533f)

That SSA rewriter had a bug where it wasn' t handling variables correctly in some kinds of loops. See 
https://github.com/KhronosGroup/SPIRV-Tools/issues/1456 

That was fixed with
https://github.com/KhronosGroup/SPIRV-Tools/pull/1453 about 6 days ago. (this [commit](https://github.com/KhronosGroup/SPIRV-Tools/commit/6fbfe1c016bd8ffaf8f59db75e660d7d9a447843) on master)


However, @PapricaJim says the problem persists with commit https://github.com/KhronosGroup/SPIRV-Tools/commit/3020104ff25a0f661e7818bd49fbf5f23e0b0e98 which is after the latest SSA rewriter fix.

I will transfer this over to a SPIRV-Tools issue.

**Comment by dneto0** [comment]
Closing this in favour of https://github.com/KhronosGroup/SPIRV-Tools/issues/1487
