### ISSUE TITLE
Use submodules for dependencies

### ISSUE THREAD

**Issue by jesta88** [google/shaderc#456]
Having git submodules inside third_party/ would help when building libraries with shaderc as a submodule (only one recursive update to get everything working).

**Comment by AWoloszyn** [comment]
This is something we have discussed in the past. There are a number of issues with submodules which means we have not gone that route as of now. 

Something that can be done now, is specifying dependencies outside of third_party. i.e. you could have shaderc and all of its dependencies in sibling submodules to your project, and then in your CMake file set SHADERC_THIRD_PARTY_ROOT_DIR. This would allow you to do a top-level git checkout --recursive and get all of the sources, and have a working build.

The downside to this approach is that you would still have to make sure to update these dependencies when updating shaderc, so that is maintenance you will have to do.

**Comment by jesta88** [comment]
Thanks, this is a very good compromise. I wasn't aware of SHADERC_THIRD_PARTY_ROOT_DIR.
