### ISSUE TITLE
Build fails due to non-ascii byte 0xe2 at commit a53d8fe2

### ISSUE THREAD

**Issue by avih** [google/shaderc#874]
Commit a53d8fe2 added (among others) the following line at `libshaderc_spvc/src/spvcir_pass.cc`:
```c
// bits, 32 bits, 64 bits, and any multiple of 32 bits ≥128
```

The byte before "128" (`>=` ?) is 0xe2 - which seems to fail the copyright check with this file, which somehow expects only valid ascii bytes, as follows:
```
Traceback (most recent call last):
  File "shaderc/utils/add_copyright.py", line 147, in <module>
    main()
  File "shaderc/utils/add_copyright.py", line 139, in main
    count += alert_if_no_copyright(*pair)
  File "shaderc/utils/add_copyright.py", line 123, in alert_if_no_copyright
    for line in contents:
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 5823: ordinal not in range(128)
```

The obvious workaround is to remove this char from this comment.

However, I'd think the copyright check should not fail if a file contains an invalid ascii byte. Those are valid in C and there's no reason the build would fail on such thing, especially when it's in a comment.

**Comment by zoddicus** [comment]
... of course ASCII vs Unicode issues would haunt me even here :-) I will take a look at this.

**Comment by zoddicus** [comment]
I have not been able to reproduce this, but I suspect from the Python side what is going is that the compiled regex is not being set to unicode mode, but instead ascii for some reason. I will put in the fix to the regex compile step to force utf-8.

On the larger is unicode allowed in C source files issue, I think it is technically in a grey area. If I recall correctly there is a set of characters specified that must be supported for source code, which are mostly the english letters, numbers, some symbols. Effectively ASCII. String literals are an exception, because they are allowed to be wide characters, which maybe UTF-8, UTF-16, or some other options. It is left to the compiler to decide on what wide character format to use for strings and what to do about non-ASCII code characters. Thus I think the most portable solution would be to restrict ourselves to the explicitly allowed characters. So I am going to also remove the offending character too.

**Comment by avih** [comment]
Thanks for handling it.

However, looking at your commit, if i apply only this part of the diff:
```diff
diff --git a/utils/add_copyright.py b/utils/add_copyright.py
index d1ede56..b4acb25 100755
--- a/utils/add_copyright.py
+++ b/utils/add_copyright.py
@@ -28,7 +28,7 @@ import re
 import sys

 COPYRIGHTRE = re.compile(
-    r'Copyright \d+ The Shaderc Authors. All rights reserved.')
+    r'Copyright \d+ The Shaderc Authors. All rights reserved.', re.UNICODE)
 COPYRIGHT = 'Copyright 2016 The Shaderc Authors. All rights reserved.'
 LICENSED = """
 Licensed under the Apache License, Version 2.0 (the "License");
```
Then it still fails.

It does work once I also replace the offending char.

**Comment by zoddicus** [comment]
> Thanks for handling it.
> 
> However, looking at your commit, if i apply only this part of the diff:
> 
> ```diff
> diff --git a/utils/add_copyright.py b/utils/add_copyright.py
> index d1ede56..b4acb25 100755
> --- a/utils/add_copyright.py
> +++ b/utils/add_copyright.py
> @@ -28,7 +28,7 @@ import re
>  import sys
> 
>  COPYRIGHTRE = re.compile(
> -    r'Copyright \d+ The Shaderc Authors. All rights reserved.')
> +    r'Copyright \d+ The Shaderc Authors. All rights reserved.', re.UNICODE)
>  COPYRIGHT = 'Copyright 2016 The Shaderc Authors. All rights reserved.'
>  LICENSED = """
>  Licensed under the Apache License, Version 2.0 (the "License");
> ```
> 
> Then it still fails.
> 
> It does work once I also replace the offending char.
> 
> EDIT
> 
> > Thus I think the most portable solution would be to restrict ourselves to the explicitly allowed characters
> 
> So I'm not sure if my result is expected?

Hmmm... I was assuming that the issue was in the compiled regex not being Unicode, but it might actually be that the read in text being treated as ASCII, due to default platform encoding. I am surprised that if doesn't die earlier when reading the file if that is the case. But there might be some sort of lazy operation going on in the system, where the line isn't actually being read/encoded until something references it.

I have rolled back the Python side fix, since the patch already fixes the underlying issue in the source file and my fix in Python was insufficient. 

I think the forward going solution here is to restrict the character set in our source code to ASCII. I am unsure on what the fix for the Python side would be, since it seems like we need to detect the character set that the file is being read in as and make sure that the regex is encoded to that, but it doesn't appear to be happening automatically. Or atleast not on systems that read in ASCII by default.

**Comment by avih** [comment]
If you need any diagnostic or info on my system or want me to run some snippet (preferably stand alone), just let me know how to grab the info you need.

FWIW, the system is Ubuntu 18.04 LTS with locale `en_US.UTF-8`, though I didn't built shaderc natively - this is a mingw cross compiling of shaderc on this system (using MXE), though python is the system native python (makes sense to me - it doesn't use mingw python on ubuntu, and I also didn't compile a mingw python anyway).

**Comment by zoddicus** [comment]
Hmmm, my system should be a Debian derivative on UTF-8 also, so I am surprised I am not seeing the same problem.

It might be something related to using mingw, since Windows I think encode some form of UTF-16, LE I think?, by default. Maybe? I am kinda grasping at straws in that regard.

Given that removing the Unicode character from the source fixes the issue, I am preferential to that solution since it is portable and Unicode issues tend to be a bit thorny. If we find this occurring often, or we have a need for wide characters in string literals I will come back to this. 

Thank you for the bug report and offer to help with further debugging.

**Comment by avih** [comment]
You were right, it seems somehow related to the mingw setup. When I build natively using:
```sh
mkdir bld &&
cd bld &&
cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DSHADERC_SKIP_TESTS=ON -DBUILD_SHARED_LIBS=OFF .. &&
ninja
```
Then it completes successfully.

Possibly worth noting that cmake is different. The native is 3.10.2 while the mingw (built as support in MXE) is 3.15.4, though I don't think it makes a difference. shaderc's configure detects the same python 3.6.8 both natively and for mingw:
```
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.8", minimum required is "3")
```
And the error message at the first post seems to indicate that the same python is used.

Anyway, if I ever figure out what's going on, I'll post here.

For now, thanks for replacing that char :)

**Comment by avih** [comment]
Thank you.
