### ISSUE TITLE
Labeling release builds

### ISSUE THREAD

**Issue by sfricke-samsung** [google/shaderc#988]
It would be helpful if there was a label (release tag or git sha) of what version the [downloadable](https://github.com/google/shaderc/blob/master/downloads.md) binaries are. I am assuming its the `v2019.1` build, but not 100% sure

**Comment by zoddicus** [comment]
I wouldn't expect those binaries to be v2019.1. Since 2019.1 was cut a few weeks ago, and I didn't explicitly create those binaries at that time. 

I would expect them to be either ToT builds or some sort of ancient build from when that page was set up. I was unfamiliar with the existence of this page until you pointed it out.

It looks like the person that set it up no longer works on teh project, so I will investigate how the binaries are being generated and update the documentation about them.

**Comment by sfricke-samsung** [comment]
Thanks, also the link was in the README.md so make sure to update if that page is removed and/or moved

**Comment by zoddicus** [comment]
I think those builds should be ToT, specifically whatever the bots most recently built successfully.

I will look into having the page list the hash for the repo they built from.
