### ISSUE TITLE
Instructions for minimal runtime glslangValidator

### ISSUE THREAD

**Issue by sfricke-samsung** [google/shaderc#989]
My main goal of shaderc is to use libshaderc as a runtime for GLSL->SPIR-V where I can't use glslangValidator offline. For x64 Windows build.

- glslangValidator.exe is `4mb`
- shaderc.lib is `273kb`
- shaderc_combined.lib is `72mb`
- shaderc_shared.dll is `4mb`

From re-reading the libshaderc readme, I still can't figure out what I actually need to simulate glslangValidator only as I only want to minimal amount of dependencies

----

Also totally correct me if I am wrong in thinking libshaderc is for only GLSL and I should be using the `glslang` repo as an interface

**Comment by zoddicus** [comment]
From a high level, if all you are wanting is the GLSL->SPIR-V functionality of glslang, you probably want to use it directly. libshaderc includes the HLSL->SPIR-V functionality also by default, and appears to expose parts of SPIRV-Tools, both of which are going be effectively bloat for you.

I would expect it would be possible to refactor libshaderc and its build rules to have an option for only GLSL->SPIR-V code, but I honestly have not idea how difficult that would be, since I primarily work on spvc.

Now for some more low-level comments:
Preface, I am not experienced with Windows programming, so I apologize if my comments are off base.

Do you have numbers for what the size hit for a compiled binary is? i.e. a trivial binary that uses the parts of the API that you intend vs a trivial binary without the library.

In general library disk sizes can be misleading for the binary size hit, because when libraries are built the compiler/linker cannot perform dead code removal, since it doesn't know how the API is going to be accessed. Looking at Linux Release build the libshader_combined.a is ~14MB, but glslc is only 6MB, so there is significant slimming occurring during the linking process.

**Comment by sfricke-samsung** [comment]
Well the reason I directed myself first here was from the [android ndk developer site](https://developer.android.com/ndk/guides/graphics/shader-compilers) that references shaderc (probably because it is in the NDK)

I am doing cross-platform and Android/Linux is not the issue, the issue is with Windows as you either need to build shaderc from source (which bloats compile time) or you need to have 4 copies of the shaderc.lib/dll as there is [4 runtimes](https://docs.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=vs-2019) and so now I need to carry 8 copies (4 for x86 and 4 for x64)

That being said, finally looked into the source and realized that libshaderc is really just a thin wrapper around everything else.

going to close this issue due to the answer being "use glslang" for the use case I proposed above
